name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Prep...
        env:
          test_var: ${{ vars.TEST_VARIABLE }}
        run: echo "prep $test_var"

      - name: Testing...
        env:
          test_var: ${{ vars.TEST_VARIABLE }}
        if: env.test_var 
        run: |
          echo "running"
          echo "$test_var"
