name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435
        with:
          python-version: 3.11

      - name: Testing...
        run: |
          pip install git+https://github.com//secure-systems-lab/securesystemslib sigstore
          python test.py
