name: Test signing
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo event_name: ${{ github.event_name }}
          echo test result [${{ github.event_name != "schedule" }}]

      - name: Test 2
        if: ${{ github.event_name != "schedule" }}
        run: |
          echo "not schedule / cron"
