name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Test gh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue list
          echo $?
          gh issue list --search "abcd"
          echo $?
          gh search issues "abcd"
          echo $?

          gh issue create --title "issue filed from CI for testing" --body "moar text"
