name: Test signing
on:
  workflow_dispatch:
  push:
    branches:
    - testbranch
    paths:
    - 'testdir/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout release tag
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - run: |
          git tag -a v0.1 -m "test tag protection"
          git push --tags
