name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      test_var: ${{ vars.TEST_VARIABLE }}
    steps:
      - uses: actions/checkout@v3

      - name: Prep...
        run: echo "prep $test_var"

      - name: Testing...
        if: env.test_var 
        run: |
          echo "running"
          echo "$test_var"
