name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Prep...
        run: echo "prep $TEST_VARIABLE"

      - name: Testing...
        if: env.TEST_VARIABLE 
        run: |
          echo "running"
          echo "$TEST_VARIABLE"
