name: Test signing
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo event_name: ${{ github.event_name }}

      - name: Test 2
        if: github.event_name != 'schedule'
        run: |
          echo "not schedule / cron"
