name: Test signing
on:
  workflow_dispatch:

  test2:
    if: ${{ github.event_name }} = "test2"
    runs-on: ubuntu-latest
    steps:
      run: |
        echo "test2"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo event_name: ${{ github.event_name }}
          echo event: ${{ github.event }}
          echo workflow_dispatch: ${{ github.event.workflow_dispatch }}
          echo schedule: ${{ github.event.schedule }}
